"""Phase-E gate: ``mql5-docs-assemble`` markdown → ``.docx`` conversion.

The assemble command takes the LLM-authored ``guide.md`` and renders
it to a Word document for the EA ship bundle. These tests pin the
markdown features the prompt asks the LLM to use (headings, tables,
fenced code, callouts, images, ``[[TOC]]``) and the soft-validation
rules that protect downstream reviewers from obviously broken guides.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from docx import Document

from vibecodekit_mql5 import docs_assemble


SAMPLE_GUIDE_MD = """\
# MyEA v1.0.0 — Hướng dẫn sử dụng

[[TOC]]

# Chương 1 — Tổng quan

EA này dùng để giao dịch trend EURUSD H1.

## 1.1 Triết lý cốt lõi

> **Lưu ý**: chỉ vào lệnh khi có xu hướng rõ ràng.

# Chương 2 — Tham số EA

| Tham số | Mặc định | Ý nghĩa |
|---|---|---|
| InpRiskMoney | 50.0 | Risk per trade |
| InpSlPips | 30 | Stop loss in pips |

# Chương 3 — Cài đặt

1. Mở MT5 → File → Open Data Folder
2. Vào MQL5/Experts
3. Copy MyEA.ex5 vào đây

# Chương 4 — Backtest

```bash
Period: H1
Symbol: EURUSD
```

# Chương 5 — Risk warnings

- Không khuyến nghị live trên broker spread > 10 pips
- Drawdown tối đa lịch sử: 12%
"""


# 10×10 RGB PNG generated by Pillow — python-docx's image probe rejects
# the hand-rolled 1×1 PNGs found in older fixtures (the CRC values
# differ slightly between encoders and python-docx's strict parser
# raises on a mismatch). Pillow ships as a transitive dependency of
# python-docx so calling out to it adds zero install surface.
_TINY_PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d494844520000000a0000000a0802000000025058ea"
    "0000001249444154789c63fccf800f30e1951db1d200412c0113b10a731300000"
    "00049454e44ae426082"
)


def _write_guide(tmp_path: Path, body: str = SAMPLE_GUIDE_MD) -> Path:
    path = tmp_path / "guide.md"
    path.write_text(body, encoding="utf-8")
    return path


def test_assemble_renders_basic_structure(tmp_path: Path) -> None:
    guide = _write_guide(tmp_path)
    out_docx = tmp_path / "MyEA.docs.docx"

    result = docs_assemble.assemble(guide, out_docx)

    assert result.ok is True
    assert out_docx.is_file()
    assert result.chapters == 5
    assert result.warnings == []  # SAMPLE_GUIDE_MD clears all validation gates

    doc = Document(str(out_docx))
    headings = [
        p.text
        for p in doc.paragraphs
        if p.style and "Heading" in p.style.name
    ]
    assert any("Tổng quan" in h for h in headings)
    assert any("Tham số EA" in h for h in headings)
    assert any("Cài đặt" in h for h in headings)


def test_assemble_emits_table_with_header_row(tmp_path: Path) -> None:
    guide = _write_guide(tmp_path)
    out_docx = tmp_path / "MyEA.docs.docx"
    docs_assemble.assemble(guide, out_docx)

    doc = Document(str(out_docx))
    assert len(doc.tables) >= 1
    table = doc.tables[0]
    assert "Tham số" in table.rows[0].cells[0].text
    assert "InpRiskMoney" in table.rows[1].cells[0].text


def test_assemble_embeds_image_when_present(tmp_path: Path) -> None:
    images = tmp_path / "images"
    images.mkdir()
    (images / "chart.png").write_bytes(_TINY_PNG)
    guide = _write_guide(
        tmp_path,
        body=SAMPLE_GUIDE_MD + "\n# Chương 6 — Charts\n\n![Chart](images/chart.png)\n",
    )
    out_docx = tmp_path / "MyEA.docs.docx"

    result = docs_assemble.assemble(guide, out_docx, images_dir=images)

    assert result.images_embedded == 1
    assert all("image not found" not in w for w in result.warnings)


def test_assemble_warns_for_missing_image(tmp_path: Path) -> None:
    guide = _write_guide(
        tmp_path,
        body=SAMPLE_GUIDE_MD
        + "\n# Chương 6 — Charts\n\n![Chart](images/missing.png)\n",
    )
    out_docx = tmp_path / "MyEA.docs.docx"

    result = docs_assemble.assemble(guide, out_docx)

    assert result.images_embedded == 0
    assert any("image not found" in w for w in result.warnings)


def test_assemble_inserts_toc_field(tmp_path: Path) -> None:
    import zipfile

    guide = _write_guide(tmp_path)
    out_docx = tmp_path / "MyEA.docs.docx"
    docs_assemble.assemble(guide, out_docx)

    with zipfile.ZipFile(out_docx) as zf:
        body_xml = zf.read("word/document.xml")
    # ToC field instruction must round-trip into ``word/document.xml`` so
    # Word knows to render a real ToC on F9.
    assert b'TOC \\o &quot;1-3&quot;' in body_xml or b'TOC \\o "1-3"' in body_xml


def test_validate_rejects_missing_h1() -> None:
    issues = docs_assemble.validate_guide_md(
        "Some prose with no leading heading\n\n## Subsection"
    )
    assert any("H1" in i for i in issues)


def test_validate_rejects_missing_toc() -> None:
    md = "# Title\n\n# Chương 1\n# Chương 2\n# Chương 3\n# Chương 4\n# Chương 5"
    issues = docs_assemble.validate_guide_md(md)
    assert any("TOC" in i.upper() for i in issues)


def test_validate_rejects_too_few_chapters() -> None:
    md = "# Title\n\n[[TOC]]\n\n# Only one chapter"
    issues = docs_assemble.validate_guide_md(md)
    assert any("Quá ít" in i for i in issues)


def test_validate_rejects_too_many_chapters() -> None:
    chapters = "\n".join(f"# Chương {n}" for n in range(1, 15))
    md = f"# Title\n\n[[TOC]]\n\n{chapters}"
    issues = docs_assemble.validate_guide_md(md)
    assert any("Quá nhiều" in i for i in issues)


def test_validate_passes_sample_guide() -> None:
    assert docs_assemble.validate_guide_md(SAMPLE_GUIDE_MD) == []


def test_assemble_surfaces_validation_warnings(tmp_path: Path) -> None:
    guide = _write_guide(tmp_path, body="No heading and no TOC marker either.")
    out_docx = tmp_path / "broken.docx"
    result = docs_assemble.assemble(guide, out_docx)

    assert result.ok is True  # validation issues are soft warnings
    assert any("H1" in w for w in result.warnings)
    assert any("TOC" in w.upper() for w in result.warnings)


def test_main_cli_round_trip(tmp_path: Path, capsys) -> None:
    guide = _write_guide(tmp_path)
    out_docx = tmp_path / "MyEA.docs.docx"
    rc = docs_assemble.main([str(guide), "--out", str(out_docx)])
    captured = capsys.readouterr()
    payload = json.loads(captured.out)

    assert rc == 0
    assert payload["chapters"] == 5
    assert payload["tables"] == 1
    assert out_docx.is_file()


def test_main_cli_missing_guide(tmp_path: Path) -> None:
    rc = docs_assemble.main(
        [
            str(tmp_path / "nope.md"),
            "--out",
            str(tmp_path / "out.docx"),
        ]
    )
    assert rc == 2


def test_assemble_renders_link_url_inline(tmp_path: Path) -> None:
    """Links must keep their URL inline so a printed copy is useful.

    Pre-fix the renderer captured the href onto the token but never
    emitted any run for the URL, so ``[MT5 manual](https://...)``
    collapsed to just ``MT5 manual`` in the docx.
    """
    md = (
        "# Title\n\n"
        "[[TOC]]\n\n"
        "# Chương 1\n\nXem thêm [MT5 manual](https://www.metatrader5.com/help).\n\n"
        "# Chương 2\n# Chương 3\n# Chương 4\n# Chương 5\n"
    )
    guide = _write_guide(tmp_path, body=md)
    out_docx = tmp_path / "links.docx"
    docs_assemble.assemble(guide, out_docx)

    doc = Document(str(out_docx))
    full_text = "\n".join(p.text for p in doc.paragraphs)
    assert "MT5 manual" in full_text
    assert "https://www.metatrader5.com/help" in full_text


def test_validate_ignores_h1_inside_code_fence() -> None:
    """``# foo`` inside a fenced code block must not count as a chapter.

    Pre-fix ``validate_guide_md`` was line-based and naively matched
    any leading ``# `` regardless of fence state, so shell snippets
    like ``# rebuild`` inside ``\\`\\`\\`bash`` inflated the chapter count.
    """
    md = (
        "# Title\n\n"
        "[[TOC]]\n\n"
        "# Chương 1\n"
        "```bash\n"
        "# fake chapter heading inside a fence\n"
        "# another one\n"
        "```\n"
        "# Chương 2\n# Chương 3\n# Chương 4\n# Chương 5\n"
    )
    assert docs_assemble.validate_guide_md(md) == []


def test_validate_ignores_toc_marker_inside_code_fence() -> None:
    """``[[TOC]]`` only counts when it sits outside a fenced code block."""
    md = (
        "# Title\n\n"
        "```text\n"
        "[[TOC]]\n"
        "```\n"
        "# Chương 1\n# Chương 2\n# Chương 3\n# Chương 4\n# Chương 5\n"
    )
    issues = docs_assemble.validate_guide_md(md)
    assert any("TOC" in i.upper() for i in issues)


def test_result_is_json_serialisable(tmp_path: Path) -> None:
    guide = _write_guide(tmp_path)
    result = docs_assemble.assemble(guide, tmp_path / "MyEA.docs.docx")
    json.dumps(asdict(result), ensure_ascii=False)
